package Swing;

import Swing.SubmenuGestionJugadores;
import Swing.SubmenuGestionEquipos;
import Swing.SubmenuGestionPartidos;
import Swing.SubmenuGestionJugadorEquipo;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author isard
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Pantallas
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGesJugador = new javax.swing.JButton();
        jButtonGesEquipos = new javax.swing.JButton();
        jButtonGesJugadorEquipo = new javax.swing.JButton();
        jButtonGesPartidos = new javax.swing.JButton();
        jButtonConsultarMultitabla = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal - Gestión Campeonato");

        jButtonGesJugador.setText("Gestion de Jugadores");
        jButtonGesJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesJugadorActionPerformed(evt);
            }
        });

        jButtonGesEquipos.setText("Gestion de Equipos");
        jButtonGesEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesEquiposActionPerformed(evt);
            }
        });

        jButtonGesJugadorEquipo.setText("Gestion de Jugador-Equipo");
        jButtonGesJugadorEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesJugadorEquipoActionPerformed(evt);
            }
        });

        jButtonGesPartidos.setText("Gestion Partidos");
        jButtonGesPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesPartidosActionPerformed(evt);
            }
        });

        jButtonConsultarMultitabla.setText("Consultar Multitabla");
        jButtonConsultarMultitabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarMultitablaActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonGesJugador)
                    .addComponent(jButtonGesEquipos)
                    .addComponent(jButtonGesJugadorEquipo)
                    .addComponent(jButtonGesPartidos)
                    .addComponent(jButtonConsultarMultitabla)
                    .addComponent(jButtonVolver))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonGesJugador)
                .addGap(25, 25, 25)
                .addComponent(jButtonGesEquipos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButtonGesPartidos)
                .addGap(18, 18, 18)
                .addComponent(jButtonGesJugadorEquipo)
                .addGap(32, 32, 32)
                .addComponent(jButtonConsultarMultitabla)
                .addGap(26, 26, 26)
                .addComponent(jButtonVolver)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGesJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesJugadorActionPerformed
        SubmenuGestionJugadores gj = new SubmenuGestionJugadores(this, true);
        gj.setVisible(true);
    }//GEN-LAST:event_jButtonGesJugadorActionPerformed

    private void jButtonGesEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesEquiposActionPerformed
        SubmenuGestionEquipos ge = new SubmenuGestionEquipos(this, true);
        ge.setVisible(true);
    }//GEN-LAST:event_jButtonGesEquiposActionPerformed

    private void jButtonGesJugadorEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesJugadorEquipoActionPerformed
        SubmenuGestionJugadorEquipo gje = new SubmenuGestionJugadorEquipo(this, true);
        gje.setVisible(true);
    }//GEN-LAST:event_jButtonGesJugadorEquipoActionPerformed

    private void jButtonGesPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesPartidosActionPerformed
        SubmenuGestionPartidos gp = new SubmenuGestionPartidos(this, true);
        gp.setVisible(true);
    }//GEN-LAST:event_jButtonGesPartidosActionPerformed

    private void jButtonConsultarMultitablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarMultitablaActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
            "La consulta multitabla está disponible desde la interfaz de consola.\n" +
            "Ejecuta la aplicación por consola y selecciona la opción 5.",
            "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonConsultarMultitablaActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Seguro que deseas salir?", "Confirmar salida",
            javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarMultitabla;
    private javax.swing.JButton jButtonGesEquipos;
    private javax.swing.JButton jButtonGesJugador;
    private javax.swing.JButton jButtonGesJugadorEquipo;
    private javax.swing.JButton jButtonGesPartidos;
    private javax.swing.JButton jButtonVolver;
    // End of variables declaration//GEN-END:variables
}
